<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzfpxz1\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzfpxz1/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMzfpxz1.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMzfpxz1\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMzfpxz1\appProdProjectContainer([
    'container.build_hash' => 'Mzfpxz1',
    'container.build_id' => '167eb98b',
    'container.build_time' => 1662692092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzfpxz1');
